"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Darlene Santes and <FULL NAME>, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: drs4423
UT EID 2:
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    # Making sure that the string is not empty
    s_length = len(s)
    if s_length == 0:
        return 0

    # Checking each possible substring
    max_length = 0
    for i in range(s_length):
        for j in range(i + 1, s_length + 1):
            # Creating ascii frequency list to check for duplicates
            frequency = [0] * 256
            no_repeats = True

            # iterating through every character in the substring, adding it to frequency list
            for char in range(i, j):
                ascii_char = ord(s[char])
                frequency[ascii_char] += 1
                # Checking if there is a duplicate
                if frequency[ascii_char] > 1:
                    no_repeats = False

            # Reassigning max length if it is valid
            if no_repeats and (j - i + 1) > max_length:
                max_length = j - i

    return max_length


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    s_length = len(s)
    if s_length == 0:
        return 0

    # Using the same logic as the N^3 solution minus one loop
    max_length = 0
    for i in range(s_length):
        frequency = [0] * 256
        no_repeats = True
        for j in range(i + 1, s_length + 1):
            ascii_char = ord(s[j - 1])
            frequency[ascii_char] += 1
            # Checking if there is a duplicate
            if frequency[ascii_char] > 1:
                no_repeats = False

            if no_repeats and (j - i) > max_length:
                max_length = j - i

    return max_length

# TODO: implement this function. You may delete this comment when you are done.
def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    pass
